[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  PUBLIC_SITE_ENV = "production"

[context.stage]
  command = "npm run build"

[context.stage.environment]
  PUBLIC_SITE_ENV = "staging"

[context.branch-deploy]
  command = "npm run build"

[context.branch-deploy.environment]
  PUBLIC_SITE_ENV = "staging"

[context.deploy-preview]
  command = "npm run build"

[context.deploy-preview.environment]
  PUBLIC_SITE_ENV = "staging"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/directorio-de-apps"
  to = "/aplicaciones-prestamo"
  status = 301

[[redirects]]
  from = "/faqs"
  to = "/preguntas-frecuente"
  status = 301

[[redirects]]
  from = "/testimonials"
  to = "/testimonios"
  status = 301

[[redirects]]
  from = "/contactanos"
  to = "/contacto"
  status = 301

[[redirects]]
  from = "/blog/aplicaciones-de-prestamos-confiables"
  to = "/blog/apps-prestamos-confiables"
  status = 301